### ISSUE TITLE
Version specific description/release notes: How?

### ISSUE THREAD

**Issue by mpern** [gradle-guides/publishing-plugins-to-gradle-plugin-portal#8]
If you check the plugins.gradle.com page of the plugin-publish plugin:
https://plugins.gradle.org/plugin/com.gradle.plugin-publish

You can see that every version has release notes as a description,.

I’m wondering how I could do that for my own plugin, I couldn’t find anything in the documentation.
https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/

**Comment by marcphilipp** [comment]
It sets the `description` of the plugin in the `pluginBundle` extension to the release notes. It seems the portal never updates the original description. That sounds more like a hack to me which is probably why it isn't documented. 😉

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #249](https://github.com/gradle/guides/issues/249) via [**ZenHub**](https://www.zenhub.com/)
